@startuml
'https://plantuml.com/sequence-diagram

title **Password authentication**

skinparam ParticipantPadding 80
skinparam style strictuml
skinparam sequenceMessageAlign center

participant Client as cli
participant Server as srv

|||
activate cli

note over cli: Enter password
note over cli: Compute password SHA512

|||

cli -> srv: POST /login

|||
activate srv

note over srv: Check password hash in DB


alt#gold #yellowgreen Success
    note over srv: Generate token
    note over srv: Store token genration time
    cli <-- srv: 200 OK
    note right: Set-Cookie:token=<token>
else #lightcoral Failure
    cli <-- srv: 401 Unauthorized
end

deactivate srv

|||

footer **Client can now send request with the token cookie to be authenticated**

@enduml
